# Labeler configuration for CTX

# Feature changes
feature.*:
  - 'src/**'
  - 'src-tauri/**'

# Bug fixes
fix.*:
  - 'src/**'
  - 'src-tauri/**'

# Documentation changes
docs.*:
  - '*.md'
  - 'docs/**'
  - '.github/**'

# CI/CD changes
ci.*:
  - '.github/workflows/**'
  - '.github/dependabot.yml'
  - '.github/labeler.yml'

# Frontend changes
frontend:
  - changed-files:
    - any-glob-to-any-file: 'src/**'

# Backend changes
backend:
  - changed-files:
    - any-glob-to-any-file: 'src-tauri/**'
