# Labeler configuration for CTX

# Feature changes
feature.*:
  - changed-files:
    - any-glob-to-any-file: 'src/**'

# Bug fixes
fix.*:
  - changed-files:
    - any-glob-to-any-file: 'src/**'

# Documentation changes
docs.*:
  - changed-files:
    - any-glob-to-any-file: '*.md'
    - any-glob-to-any-file: 'docs/**'

# CI/CD changes
ci.*:
  - changed-files:
    - any-glob-to-any-file: '.github/workflows/**'
    - any-glob-to-any-file: '.github/dependabot.yml